# make sure that the environment variables ARCH and CROSS_COMPILE
# are set for your architecture and cross compiler.
# And that KDIR points to the kernel to build against.
#
# e.g.:
# export ARCH=arm
# export CROSS_COMPILE=arm-linux-gnueabihf-
# export KDIR=../linux

MODULE_NAME := tfa98xx_dlkm

# debugging support
TFA_DEBUG := 0

ccflags-y += -I$(srctree)/$(src)/inc
ccflags-y += -Werror

obj-$(CONFIG_SND_SOC_TFA9894) := $(MODULE_NAME).o

$(MODULE_NAME)-objs += src/tfa98xx.o
$(MODULE_NAME)-objs += src/tfa_container.o
$(MODULE_NAME)-objs += src/tfa_dsp.o
$(MODULE_NAME)-objs += src/tfa_init.o

# Disable enum conversion warning
subdir-ccflags-y := $(call cc-disable-warning, enum-conversion)

ifeq ($(TFA_DEBUG),1)
ccflags-y += -DTFA_DEBUG -DDEBUG
$(MODULE_NAME)-objs += src/tfa_debug.o
endif
